const router = require('express').Router();
const asyncHandler = require('express-async-handler');
const SideProjectController = require('../controllers/SideProjectController');

/**
 * @group Side Projects
 *
 * View all side projects
 *
 * This endpoint's response was gotten via a "response call"—
 * Scribe **called our API** in a test environment to get a sample response.
 */
router.get('/', asyncHandler(SideProjectController.index));

/**
 * @group Side Projects
 *
 * Start a new side project
 *
 * _Even though we both know you'll never finish it._
 *
 * This endpoint's body parameters were automatically generated by Scribe
 * from the controller's code. Check out the source! </aside>
 *
 * @authenticated
 */
router.post('/:id(\\d+)', asyncHandler(SideProjectController.store));

/**
 * @group Side Projects
 *
 * Finish a side project
 *
 * Hmmm.🤔
 */
router.post('/:id(\\d+)', asyncHandler(SideProjectController.finish));

/**
 * @group Side Projects
 *
 * View a side project
 *
 * The 404 sample is gotten from a "response file".
 *
 * <aside class="success">Also, pretty cool: this endpoint's (and some others) URL parameters were figured out entirely by Scribe!</aside>
 *
 * @responseFile 404 scenario="Side project not found" storage/responses/not_found.json {"resource": "Side project"}
 */
router.get('/:id(\\d+)', asyncHandler(SideProjectController.show));

/**
 * @group Side Projects
 *
 * Update a side project
 */
router.post('/:id(\\d+)', asyncHandler(SideProjectController.update));

/**
 * @group Side Projects
 *
 * Delete a side project
 *
 * @response 204 scenario="Nothing to see here"
 */
router.delete('/:id(\\d+)', asyncHandler(SideProjectController.destroy));

module.exports = router;
